version: '3.9'
services: 
  front:
    build: ./front-app
    restart: always
    volumes:
      - './:/usr/src/app'
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    